export const customStyles = {
  overlay: {
    backgroundColor: '#ebf1fb',
    zIndex: 1300,
  },
  content: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    zIndex: '1200',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    marginTop: '20px',
    transform: 'translate(-50%, -50%)',
    maxWidth: '100%',
    width: '600px',
    height: '750px',
    padding: '40px',
    boxShadow: '2px 2px 2px #0f0f0f',
    border: 'none',
    borderRadius: '12px',
    backgroundColor: '#ebecf0',
    color: '#545454',
    textShadow: '1px 4px 6px #b1b4bf, 1px -2px 2px #fff',
  },
};
export const customStylesInsideModal = {
  overlay: {
    backgroundColor: 'rgba(142,154,175, 0.9)',
    zIndex: 1301,
  },
  content: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    zIndex: '1201',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    maxWidth: '100%',
    width: '600px',
    height: '900px',
    boxShadow: '2px 2px 2px #0f0f0f',
    border: 'none',
    borderRadius: '12px',
    backgroundColor: '#ebecf0',
    color: '#545454',
    textShadow: '1px 4px 6px #b1b4bf, 1px -2px 2px #fff',
  },
};
